### ISSUE TITLE
Creating a Skeleton project results in error

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#25]
I’ve tried creating a skeleton project for R2k, and here’s what I’ve got:

![skeleton-project-error](https://user-images.githubusercontent.com/3201243/32075362-44b4fe82-baa5-11e7-9772-ff9547936ec1.png)

Here’s what I see in the console:
```
java.lang.NullPointerException
	at r48.io.r2k.chunks.ArrayR2kStruct.fromRIO(ArrayR2kStruct.java:34)
	at r48.io.r2k.chunks.R2kObject.fromRIOISF(R2kObject.java:109)
	at r48.io.r2k.obj.ldb.Actor.fromRIO(Actor.java:133)
	at r48.io.r2k.chunks.SparseArrayHR2kStruct.fromRIO(SparseArrayHR2kStruct.java:37)
	at r48.io.r2k.chunks.R2kObject.fromRIOISF(R2kObject.java:109)
	at r48.io.r2k.obj.ldb.Database.fromRIO(Database.java:166)
	at r48.io.r2k.files.DatabaseIO.writeLdb(DatabaseIO.java:37)
	at r48.io.R2kObjectBackend.saveObjectToFile(R2kObjectBackend.java:104)
	at r48.dbs.ObjectDB.ensureSaved(ObjectDB.java:99)
	at r48.dbs.ObjectDB.ensureAllSaved(ObjectDB.java:214)
	at r48.AppMain$13.run(AppMain.java:479)
	at gabien.ui.UIPopupMenu.optionExecute(UIPopupMenu.java:80)
	at gabien.ui.UIAutoclosingPopupMenu.optionExecute(UIAutoclosingPopupMenu.java:33)
	at gabien.ui.UIPopupMenu.handleClick(UIPopupMenu.java:75)
	at gabien.ui.UIWindowView.handleClick(UIWindowView.java:113)
	at gabien.ui.WindowCreatingUIElementConsumer.runTick(WindowCreatingUIElementConsumer.java:82)
	at gabienapp.Application.gabienmain(Application.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at gabien.Main.main(Main.java:53)
```

No .ldb file is created, and attempting to save all modified files triggers the same error.

**Comment by 20kdc** [comment]
Hopefully fixed now.

**Comment by rohkea** [comment]
Fixed, thanks!
