### ISSUE TITLE
Skeleton project synthesis is broken

### ISSUE THREAD

**Issue by rohkea** [20kdc/gabien-app-r48#35]
When trying to create a Skeleton RM2k\[3\] project, an error occurs: ‘Error saving object: RPG_RT.ldb, java.lang.NullPointerException’. Trying to do ‘Save all modified files’ doesn’t help.

Here’s what is written in the console:
```
java.lang.NullPointerException
        at r48.io.r2k.chunks.ArrayR2kStruct.fromRIO(ArrayR2kStruct.java:43)
        at r48.io.r2k.chunks.R2kObject.fromRIOISF(R2kObject.java:135)
        at r48.io.r2k.obj.ldb.Database.fromRIO(Database.java:191)
        at r48.io.r2k.files.DatabaseIO.writeLdb(DatabaseIO.java:37)
        at r48.io.R2kObjectBackend.saveObjectToFile(R2kObjectBackend.java:118)
        at r48.dbs.ObjectDB.ensureSaved(ObjectDB.java:102)
        at r48.dbs.ObjectDB.ensureAllSaved(ObjectDB.java:246)
        at r48.AppMain$14.run(AppMain.java:517)
        at gabien.ui.UIButton.handlePointerBegin(UIButton.java:55)
        at gabien.ui.UIElement$UIPanel.handlePointerBegin(UIElement.java:343)
        at gabien.ui.UIElement$UIPanel.handlePointerBegin(UIElement.java:343)
        at gabien.ui.UIElement$UIPanel.handlePointerBegin(UIElement.java:343)
        at gabien.ui.UIElement$UIPanel.handlePointerBegin(UIElement.java:343)
        at gabien.ui.IPointerReceiver$TransformingElementPointerReceiver.handlePointerBegin(IPointerReceiver.java:71)
        at gabien.ui.IPointerReceiver$PointerConnector.handlePointerBegin(IPointerReceiver.java:41)
        at gabien.ui.UIWindowView.handlePointerBegin(UIWindowView.java:280)
        at gabien.ui.WindowCreatingUIElementConsumer.runTick(WindowCreatingUIElementConsumer.java:100)
        at gabienapp.Application.gabienmain(Application.java:213)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at gabien.Main.main(Main.java:58)
```

**Comment by 20kdc** [comment]
Should be gone. There's a bunch of chunks that I made optional in the schema but forgot to make optional elsewhere.

**Comment by 20kdc** [comment]
Given the thumbs-up-emoji, assuming fixed. Reopen if not the case.
